### Create Employee
POST http://localhost:8112/api/v1/employee
Content-Type: application/json

{
  "name": "Jill Jenkins",
  "salary": 139082,
  "age": 48,
  "title": "Financial Advisor"
}

### Get All Employees
GET http://localhost:8111/employees
Accept: application/json

### Get Employee By ID
GET http://localhost:8111/employees/d005f39a-beb8-4390-afec-fd54e91d94ee
Accept: application/json

### Delete Employee
DELETE http://localhost:8112/api/v1/employee/d005f39a-beb8-4390-afec-fd54e91d94ee
Accept: application/json
